# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollID', models.IntegerField(help_text='Poll ID')),
                ('IP', models.CharField(help_text='Recipient IP address', max_length=16)),
                ('text', models.CharField(help_text='Poll entry', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
