# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-28 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='pollID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create.poll'),
        ),
    ]
